# Generated by Django 4.2.6 on 2023-10-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_result', models.BooleanField()),
                ('ack', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HwType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TerritorialDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dashboard.zone')),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('oss', models.IntegerField()),
                ('hw_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.hwtype')),
                ('site_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.sitecontroller')),
                ('territorial_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.territorialdivision')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('alarm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.alarm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.site')),
                ('site_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.sitecontroller')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dashboard_a_name_757e15_idx')],
            },
        ),
        migrations.AddField(
            model_name='alarm',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_cell', to='dashboard.cell'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='delegate_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_delegate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarm',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_site', to='dashboard.site'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='site_controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.sitecontroller'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_type', to='dashboard.alarmtype'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['name'], name='dashboard_s_name_7e38c1_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['created_at'], name='dashboard_a_created_d3be60_idx'),
        ),
    ]
