# Generated by Django 4.2.6 on 2023-10-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='delegate_to',
        ),
    ]
