# Generated by Django 4.2.6 on 2023-10-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_alarm_delegate_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='site_controller',
        ),
    ]
