# Generated by Django 4.2.6 on 2023-10-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_alarm_site_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_site', to='dashboard.site', verbose_name='Site/Object'),
        ),
    ]
